# Generated by Django 2.2.5 on 2019-09-08 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_things_more_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='things',
            name='more_description',
        ),
    ]
