# Generated by Django 2.2.5 on 2019-09-08 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_remove_things_more_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='things',
            name='description_more',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
