# Generated by Django 2.2.5 on 2019-09-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0005_things_description_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='things',
            name='description_more',
            field=models.TextField(blank=True),
        ),
    ]
