# Generated by Django 2.2.5 on 2019-09-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0006_auto_20190908_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='things',
            name='description_more',
            field=models.TextField(blank=True, null=True),
        ),
    ]
