# Generated by Django 2.2.5 on 2019-09-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0007_auto_20190909_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='things',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in process', 'In process'), ('done', 'Done')], default='new', max_length=40),
        ),
    ]
